detect if github token is available, use git diff exitcode to detect changes

diff --git a/.github/workflows/pr-format.yml b/.github/workflows/pr-format.yml
--- a/.github/workflows/pr-format.yml
+++ b/.github/workflows/pr-format.yml
@@ -12,7 +12,7 @@ jobs:
     steps:
       - name: Clone the repository
         uses: actions/checkout@v3
-      - name: Checkout the pull request code
+      - name: Checkout the pull request code # this checks out the actual branch so that one can commit into it
         if: github.event_name == 'issue_comment'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -35,17 +35,26 @@ jobs:
             sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' "$filename"
           done
       - name: Report problems
-        if: github.event_name == 'pull_request'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        if: github.event_name == 'pull_request' && env.GITHUB_TOKEN != ''
         run: |
-          if [ `git status -s | wc -l` -ne 0 ]
+          if git diff --exit-code --quiet
           then gh pr comment ${{ github.event.number }} --body \
+          ":green_circle: &nbsp;Commit ${{ github.event.pull_request.head.sha }} is formatted properly."
+          else gh pr comment ${{ github.event.number }} --body \
           ":red_square: &nbsp;Commit ${{ github.event.pull_request.head.sha }} requires formatting!\
           "$'\n\n'"Required formatting changes summary:\
           "$'\n```\n'"`git diff --stat`"$'\n```'
-          else gh pr comment ${{ github.event.number }} --body \
-          ":green_circle: &nbsp;Commit ${{ github.event.pull_request.head.sha }} is formatted properly."
+          fi
+      - name: Fail on formatting problems
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        if: github.event_name == 'pull_request' && env.GITHUB_TOKEN == '' # pull from another repository cannot comment because there's no token
+        run: |
+          if git diff --exit-code --quiet
+          then echo "Looks OK"
+          else echo "Formatting fixes required!"; git diff -p ; exit 1
           fi
       - name: Commit fixes
         if: github.event_name == 'issue_comment'
